version: '3.8'
services:
  logcollector:
    container_name: logCollector
    build: .
    environment:
      TZ: Europe/Madrid
    ports:
      - 2896:2896
    volumes:
      - ./config/nodes.yaml:/usr/src/config/nodes.yaml
      - ./config/tpv_rsa.pem:/usr/src/ssh/tpv_rsa.pem:ro
    restart: unless-stopped
